version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      golang-x:
        patterns:
          - "golang.org/x/*"
      grpc-proto:
        patterns:
          - "google.golang.org/grpc"
          - "google.golang.org/protobuf"
          - "google.golang.org/genproto/*"
          - "github.com/golang/protobuf"
          - "github.com/gogo/protobuf"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
